app = "diacritical"
primary_region = "iad"

kill_signal = "SIGTERM"
kill_timeout = 5

[deploy]
  release_command = "/app/bin/migrate"

[[services]]
  processes = ["app"]
  internal_port = 4000
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 750

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/hello"
    protocol = "http"

    [services.http_checks.headers]
      X-Forwarded-Host = "example.com"
      X-Forwarded-Port = "4001"
      X-Forwarded-Proto = "https"

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
  size = "shared-cpu-1x"
  memory = 512
