app = "diacritical"
primary_region = "iad"

kill_timeout = 5
kill_signal = "SIGTERM"

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 750
    type = "connections"

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/hello"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443
