jobs:
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    name: Fly.io Deployment
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl deploy --remote-only
  test:
    env:
      MIX_ENV: test
    name: Erlang/OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }} / Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v4
      - env:
          cache-name: mix deps.get
        name: Run actions/cache@v4 [${{ env.cache-name }}]
        uses: actions/cache@v4
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.lock') }}"
          path: dep
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - env:
          cache-name: mix compile
        name: Run actions/cache@v4 [${{ env.cache-name }}]
        uses: actions/cache@v4
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.exs', 'mix.lock') }}"
          path: _build
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - env:
          cache-name: mix npm.install
        name: Run actions/cache@v4 [${{ env.cache-name }}]
        uses: actions/cache@v4
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('asset/**/package.json', 'asset/**/package-lock.json') }}"
          path: asset/**/node_modules
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix format --check-formatted
      - run: mix credo --all-priorities
      - run: mix dialyzer --format github
      - run: mix asset.setup
      - run: mix asset.build
      - run: mix test
    strategy:
      matrix:
        elixir-version: ["1.18.4"]
        node-version: ["24.4.1"]
        os: ["ubuntu-24.04"]
        otp-version: ["28.0.2"]

name: CI/CD

on:
  push:
    tags:
      - v0
