jobs:
  test:
    env:
      MIX_ENV: test
    name: Erlang/OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
      - uses: actions/checkout@v4
      - env:
          cache-name: mix deps.get
        name: Run actions/cache@v4 [${{ env.cache-name }}]
        uses: actions/cache@v4
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.lock') }}"
          path: dep
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - env:
          cache-name: mix compile
        name: Run actions/cache@v4 [${{ env.cache-name }}]
        uses: actions/cache@v4
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.exs', 'mix.lock') }}"
          path: _build
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix format --check-formatted
      - run: mix credo --all-priorities
      - run: mix dialyzer --format github
      - run: mix test
    strategy:
      matrix:
        elixir-version: ["1.18.4"]
        os: ["ubuntu-24.04"]
        otp-version: ["28.0.1"]

name: CI

on:
  push:
    tags:
      - v0
